source 'http://rubygems.org'

gem 'rails', '4.0.0.rc1'
gem 'combustion'
gem 'nokogiri'
gem 'rspec-rails'
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'sqlite3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'sitemap_generator', :path => '../sitemap_generator'
